### ISSUE TITLE
error: lvalue required as increment operand

### ISSUE THREAD

**Issue by jakelewis3d** [melizalab/libtfr#10]
pip install libtfr is generating some errors while building wheel.
Ubuntu 22.04 , Python 3.10,  gcc 11.2, Cython 0.29.30
Lots of deprecation warnings, but two types of error are stopping the build:

1)
      src/libtfr.c:26109:5: error: lvalue required as increment operand

      26109 |     ++Py_REFCNT(o);

perhaps you are building with an earlier version of gcc, or with a different compiler altogether, that will accept this syntax. 
This project had similar issues https://bugs.launchpad.net/lxml/+bug/1881960 , but claimed it was fixed with Cython 0.29.20, and I'm running 29.30.  Any suggestions?

2) src/libtfr.c:27835:26: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’

      27835 |   __pyx_type_6libtfr_mfft.tp_print = 0;
      
      I understand tp_print was dropped in Python 3.9,   do I need to compile against Python 3.8 or is there another newer option?

Is there a prebuilt wheel for debian / ubuntu?
      
      Here is the error in full:

pip install libtfr

Collecting libtfr

  Using cached libtfr-2.1.5.tar.gz (193 kB)

  Installing build dependencies ... done

  Getting requirements to build wheel ... done

  Installing backend dependencies ... done

  Preparing metadata (pyproject.toml) ... done

Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from libtfr) (1.21.5)

Building wheels for collected packages: libtfr

  Building wheel for libtfr (pyproject.toml) ... error

  error: subprocess-exited-with-error

  

  × Building wheel for libtfr (pyproject.toml) did not run successfully.

  │ exit code: 1

  ╰─> [203 lines of output]

      running bdist_wheel

      running build

      running build_ext

      creating tmp

      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c /tmp/tmpcwfbv5ea.cpp -o tmp/tmpcwfbv5ea.o -ffast-math

      creating build

      creating build/temp.linux-x86_64-3.10

      creating build/temp.linux-x86_64-3.10/src

      x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -Iinclude -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.10 -c src/libtfr.c -o build/temp.linux-x86_64-3.10/src/libtfr.o -ffast-math

      In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1969,

                       from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,

                       from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,

                       from src/libtfr.c:613:

      /usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]

         17 | #warning "Using deprecated NumPy API, disable it with " \

            |  ^~~~~~~

      In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,

                       from src/libtfr.c:613:

      src/libtfr.c: In function ‘__pyx_pf_6libtfr_4mfft_6tapers___get__’:

      src/libtfr.c:3247:70: warning: passing argument 6 of ‘(PyObject * (*)(PyTypeObject *, int,  const npy_intp *, int,  const npy_intp *, void *, int,  int,  PyObject *))*(PyArray_API + 744)’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]

       3247 |   __pyx_t_1 = PyArray_SimpleNewFromData(2, __pyx_v_dims, NPY_DOUBLE, mtm_tapers(__pyx_v_self->_mfft)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 68, __pyx_L1_error)

            |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:122:21: note: in definition of macro ‘PyArray_SimpleNewFromData’

        122 |                     data, 0, NPY_ARRAY_CARRAY, NULL)

            |                     ^~~~

      src/libtfr.c:3247:70: note: expected ‘void *’ but argument is of type ‘const double *’

       3247 |   __pyx_t_1 = PyArray_SimpleNewFromData(2, __pyx_v_dims, NPY_DOUBLE, mtm_tapers(__pyx_v_self->_mfft)); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 68, __pyx_L1_error)

            |                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:122:21: note: in definition of macro ‘PyArray_SimpleNewFromData’

        122 |                     data, 0, NPY_ARRAY_CARRAY, NULL)

            |                     ^~~~

      src/libtfr.c: In function ‘__pyx_pf_6libtfr_4mfft_18mtstft_pt’:

      src/libtfr.c:6534:33: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]

       6534 |   for (__pyx_t_9 = 0; __pyx_t_9 < __pyx_t_15; __pyx_t_9+=1) {

            |                                 ^

      src/libtfr.c: In function ‘__pyx_f_6libtfr_hc2cmplx’:

      src/libtfr.c:9344:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]

       9344 |   __pyx_v_buf = mtm_buffer(__pyx_v_mtm);

            |               ^

      src/libtfr.c: In function ‘__pyx_tp_dealloc_6libtfr_mfft’:

      src/libtfr.c:26109:5: error: lvalue required as increment operand

      26109 |     ++Py_REFCNT(o);

            |     ^~

      src/libtfr.c:26111:5: error: lvalue required as decrement operand

      26111 |     --Py_REFCNT(o);

            |     ^~

      src/libtfr.c: In function ‘__pyx_tp_dealloc_array’:

      src/libtfr.c:26249:5: error: lvalue required as increment operand

      26249 |     ++Py_REFCNT(o);

            |     ^~

      src/libtfr.c:26251:5: error: lvalue required as decrement operand

      26251 |     --Py_REFCNT(o);

            |     ^~

      src/libtfr.c: In function ‘__pyx_tp_dealloc_memoryview’:

      src/libtfr.c:26538:5: error: lvalue required as increment operand

      26538 |     ++Py_REFCNT(o);

            |     ^~

      src/libtfr.c:26540:5: error: lvalue required as decrement operand

      26540 |     --Py_REFCNT(o);

            |     ^~

      src/libtfr.c: In function ‘__pyx_tp_dealloc__memoryviewslice’:

      src/libtfr.c:26777:5: error: lvalue required as increment operand

      26777 |     ++Py_REFCNT(o);

            |     ^~

      src/libtfr.c:26779:5: error: lvalue required as decrement operand

      26779 |     --Py_REFCNT(o);

            |     ^~

      src/libtfr.c: In function ‘__Pyx_modinit_type_init_code’:

      src/libtfr.c:27835:26: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’

      27835 |   __pyx_type_6libtfr_mfft.tp_print = 0;

            |                          ^

      src/libtfr.c:27846:25: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’

      27846 |   __pyx_type___pyx_array.tp_print = 0;

            |                         ^

      src/libtfr.c:27851:31: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’

      27851 |   __pyx_type___pyx_MemviewEnum.tp_print = 0;

            |                               ^

      src/libtfr.c:27866:30: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’

      27866 |   __pyx_type___pyx_memoryview.tp_print = 0;

            |                              ^

      src/libtfr.c:27879:35: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’

      27879 |   __pyx_type___pyx_memoryviewslice.tp_print = 0;

            |                                   ^

      src/libtfr.c: In function ‘__Pyx_ParseOptionalKeywords’:

      src/libtfr.c:29897:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29897 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                     ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29897:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]

      29897 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                     ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here

        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(

            |                                             ^~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29897:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29897 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                     ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29897:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29897 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                     ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29897:21: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]

      29897 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                     ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here

        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(

            |                                             ^~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29897:21: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29897 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                     ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29913:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29913 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                         ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29913:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]

      29913 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                         ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here

        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(

            |                                             ^~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29913:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29913 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                         ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29913:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29913 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                         ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29913:25: warning: ‘PyUnicode_AsUnicode’ is deprecated [-Wdeprecated-declarations]

      29913 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                         ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:580:45: note: declared here

        580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(

            |                                             ^~~~~~~~~~~~~~~~~~~

      src/libtfr.c:29913:25: warning: ‘_PyUnicode_get_wstr_length’ is deprecated [-Wdeprecated-declarations]

      29913 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :

            |                         ^

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here

        446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {

            |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~

      src/libtfr.c: In function ‘__Pyx_decode_c_string’:

      src/libtfr.c:30831:9: warning: ‘PyUnicode_FromUnicode’ is deprecated [-Wdeprecated-declarations]

      30831 |         return PyUnicode_FromUnicode(NULL, 0);

            |         ^~~~~~

      In file included from /usr/include/python3.10/unicodeobject.h:1046,

                       from /usr/include/python3.10/Python.h:83,

                       from src/libtfr.c:4:

      /usr/include/python3.10/cpython/unicodeobject.h:551:42: note: declared here

        551 | Py_DEPRECATED(3.3) PyAPI_FUNC(PyObject*) PyUnicode_FromUnicode(

            |                                          ^~~~~~~~~~~~~~~~~~~~~

      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

  ERROR: Failed building wheel for libtfr

Failed to build libtfr

ERROR: Could not build wheels for libtfr, which is required to install pyproject.toml-based projects

**Comment by jakelewis3d** [comment]
I made some changes to libtfr.c on my fork that will allow compilation under Python 3.10. https://github.com/jakelewis3d/libtfr
I can't guarantee that remarking out tp_print will work for every use case though.
The first line of the code states it was generated by Cython, although I can't find the source. Perhaps rerunning with a more modern Cython will solve this issue.

**Comment by dmeliza** [comment]
I think this has been fixed now. I switched to Github Actions and tests are passing for Python 3.7 through 3.10.  I am going to close the issue but please feel free to reopen if it is still broken for you.
