### ISSUE TITLE
Use of uninitialized memory and incorrect stride with even window sizes

### ISSUE THREAD

**Issue by xyzzy42** [melizalab/libtfr#14]
Testing under valgrind found that there was data in the FFT output that was based on uninitialized memory.  This only happens when the window size is even.

I traced this back to `hermf()`.  When `N` is even, it's reduced by 1 and the `Htemp` matrix is effectively only N-1 × M, or Np-1 × K.  This is copied into `mtm->tapers` and will be `K` values short.  The full tapers array, (Np * K), is used as input to the FFT.  Each taper will be one short, so the stride is wrong, and they'll be offset too.

**Comment by dmeliza** [comment]
This looks like a pretty serious error, thank you for catching it. I'm swamped for the next few weeks but would be very happy to look at a PR.

**Comment by xyzzy42** [comment]
I'm a software engineer, not a mathematician, so I'm not all that familiar with Hermite functions.  But armed with the sophomoric knowledge of wikipedia, I mostly see what the code is doing.  Or at least think I do.

tt[i] is _x_, P is the Hermite polynomial, zeroth to Mth are calculated through a recurrence.  Htemp is the Hermite function _ψ(x)_, except there is a constant factor of √dt in there.  Dh is the derivative of Htemp, _Ψ'(x)_, but there an additional factor of dt.  Don't know why the dt appears, but note that dt = _d/di_ tt(i), so it's probably related to that.

But, it's not clear to me why only odd windows sizes work.  Is it important that tt[N/2] be zero?  I.e., what is the proper fix, disallow even window sizes, remove the special case -1 from even sizes, or alter the calculation in some way for even sizes?

**Comment by dmeliza** [comment]
I'm also not a mathematician or a software engineer, just a humble neuroscientist. I appreciate you taking a close look at the code. My main reference in writing this was the Xiao and Flandrin 2007 IEEE paper I cite in the README and the MATLAB code on their website (http://perso.ens-lyon.fr/patrick.flandrin/multitfr.html), but neither gives an explanation of why the window sizes need to be odd. If I had to guess, maybe it has something to do with the symmetry? An odd number of samples would ensure that the middle sample is at t=0. But I don't know what the practical consequences of using an even number of samples would be.

I would lean toward disallowing even window sizes until we have more information.

**Comment by dmeliza** [comment]
Patrick Flandrin, the MATLAB code and paper author, confirms that the odd number of samples is required for symmetry of the Hermite functions. So the correct solution is for the code to disallow even window sizes.

**Comment by dmeliza** [comment]
Fixed in 37256cd
