### ISSUE TITLE
Spectrogram shape mismatches

### ISSUE THREAD

**Issue by lianabagh** [melizalab/libtfr#22]
Hi,  
I am getting different number of time frames for some audios where I run spectrogram generation from torchaudio and reassigned spectrogram from libtfr. It is a one frame difference. I found in the code that the SPECFRAMES are calculated with this formula. 
SPEC_NFRAMES(mtm,signal_size,step_size) ((signal_size - mtm->npoints)/step_size + 1). Is it right?
Cause it didn't match in my examples with the actual frames that I get from this algorithm.

**Comment by dmeliza** [comment]
This library will pad the input with zeros if there is an incomplete frame at the end of the signal. You can always drop this frame if you don't want to do this.
