### ISSUE TITLE
libtfr - develop windows wheels uploaded

### ISSUE THREAD

**Issue by carlkl** [melizalab/libtfr#4]
Due to the eager needs of a colleague of mine (see https://github.com/xaratustrah/iq_suite) I took the latest develop branch (https://github.com/melizalab/libtfr/commit/9be7ccd4f72bf0829de8d607ce7cb5afb7d7ba56) and deployed Windows wheels on https://anaconda.org/carlkl/libtfr. These builds are not meant for production but for testing purposes. 

Install these wheels with: `pip install -i https://pypi.anaconda.org/carlkl/simple libtfr`

The wheels are self-contained. FFTW3 and OpenBLAS (for Lapack routines) are linked statically into the `libtfr.pyd` binary file.

Python-3.5 support is not possible today, as these wheels are compiled with [mingwpy](https://mingwpy.github.io).

**Comment by dmeliza** [comment]
Thanks! This is very useful as I don't have a way to test the code on Windows.

**Comment by carlkl** [comment]
BTW: fftw is used without multithreading support at the moment. Is this planned for the future?

**Comment by dmeliza** [comment]
I tested this many years ago and didn't see much of an improvement. Obviously this could be revisited, but it's not high on my agenda. I've created a separate issue for this and would be happy to look at a pull request.
